### ISSUE TITLE
commit message 규칙을 정리한다.

### ISSUE THREAD

**Issue by ecsimsw** [var-myeong-so/our-issues#1]

**Comment by Yunkeun** [comment]
[Angular Commit Convention](https://velog.io/@outstandingboy/Git-%EC%BB%A4%EB%B0%8B-%EB%A9%94%EC%8B%9C%EC%A7%80-%EA%B7%9C%EC%95%BD-%EC%A0%95%EB%A6%AC-the-AngularJS-commit-conventions) 을 확인한다.
