### ISSUE TITLE
Spring data elasticsearch 를 공부한다.

### ISSUE THREAD

**Issue by Yunkeun** [var-myeong-so/our-issues#14]
[Spring-boot-Elastic-stack-environment](https://github.com/ecsimsw/Spring-boot-Elastic-stack-environment) 를 개인 저장소로 포크하여 여러 가지 작업을 해본다.

**Comment by ecsimsw** [comment]
1. 소스 코드 임의로 하나 올려보기
2. 소스 데이터 안에서 검색해보기
