### ISSUE TITLE
변수명을 추출할 수 있는 정규식을 고민한다.

### ISSUE THREAD

**Issue by Yunkeun** [var-myeong-so/our-issues#18]
패키지명, 클래스명, 메소드, 변수명을 필터링할 수 있는 방법을 고민한다.

**Comment by Yunkeun** [comment]
spring data
https://docs.spring.io/spring-data/commons/docs/current/reference/html/

**Comment by Yunkeun** [comment]
클래스명은 크롤링을 통해 필터링을 한다.
따라서, 변수명에 대한 정규식만을 고민한다.

**Comment by ecsimsw** [comment]
"(?<=([a-zA-Z0-9_][\\s]))([a-zA-Z0-9_]*)(?=(\\s=))"
