### ISSUE TITLE
기술 스택 사용 이유를 작성한다.

### ISSUE THREAD

**Issue by Yunkeun** [var-myeong-so/our-issues#19]
@ecsimsw Docker, Elasticsearch
@Jaeheon-So React
@Yunkeun Spring Boot, Nginx

**Comment by ecsimsw** [comment]
Docker : 개발/운영 환경을 이미지화하여, 서버 애플리케이션 구동 환경을 동일하게, 쉽게 구축할 수 있도록 하기 위해 docker를 사용하였다.

**Comment by ecsimsw** [comment]
ELK stack : 데이터 수집/가공/검색/시각화를 담당하는 모듈로 구성되어, 역색인 기법 기반의 검색 엔진과 사용을 위한 기술을 제공한다.

**Comment by Yunkeun** [comment]
Spring Boot : 복잡한 설정 없이 제공하는 기능으로 편리하게 개발할 수 있어 비즈니스 로직에만 집중할 수 있다. 보다 쉽고 빠르게 개발할 수 있으므로 Spring Boot를 사용하였다.

**Comment by Yunkeun** [comment]
Nginx : 사용자에 비례하여 많은 thread 생성으로 메모리와 CPU 낭비가 심한 Apache에 비해 동시에 많은 연결을 처리가 가능한 nginx를 사용하였다.

**Comment by Jaeheon-So** [comment]
React : 데이터의 생산성과 유지보수를 용이하게 해주며 상태변화가 일어나 생기는 랜더링 과정반복에 의해 발생하는 비효율성을 최소화 할 수 있다.
