### ISSUE TITLE
프로젝트명, 패키지명, star 수 등 코드 크롤링 데이터를 추가한다.

### ISSUE THREAD

**Issue by ecsimsw** [var-myeong-so/our-issues#32]
추가 크롤링 데이터 목록

- 프로젝트명
- 패키지명
- Star 수
- 유저 / Organization 정보

=> 수정 필요 부분 
: CodeFile의 프로퍼티 추가 / CrawlerService.execute() 내용 수정

**Comment by Yunkeun** [comment]
유저 정보는 필요한 이유가 무엇인가요??

**Comment by ecsimsw** [comment]
변수명을 검색한 검색 결과를 출력할 때 해당 코드의 작성 유저 또는 Organization 이 표시되면 해당 코드를 보다 신뢰할 수 있을 것이라고 생각했습니다.

아래는 유사한 서비스의 검색 결과입니다. 여기서 `microsoft`가 예시가 될 수 있을 것 같습니다.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/46060746/167290839-abdd4c25-e459-4454-8f66-f023b2514d97.png">

**Comment by Yunkeun** [comment]
<img width="362" alt="스크린샷 2022-05-09 오전 1 42 05" src="https://user-images.githubusercontent.com/70425484/167306270-0a531ccc-1c1c-459f-aa7a-e0c274fae3d9.png">

CodeFile을 다음과 같이 수정해서 feature/github-crawling에서 반영할까요?
수정하는 경우 SpringElkApplication 파일도 수정이 들어갑니다.
